name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31

      - name: Run tests
        run: nix build

  lint:
    name: Lint
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31

      - name: Run lint
        run: nix flake check --impure
